services:
  - type: web
    name: dinner-bell-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: dinner-bell.onrender.com,localhost,127.0.0.1
    healthCheckPath: /health
    autoDeploy: true
