# Generated by Django 4.2.29 on 2026-03-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('directions', models.JSONField(default=list)),
                ('prep_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('cook_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('servings', models.PositiveIntegerField(default=4)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_made', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
